version: "3.9"

services:
  traefik:
    image: traefik:v2.10
    command:
      - "--configFile=/traefik.yml" # Path to Traefik configuration
    volumes:
      - "./traefik.yml:/traefik.yml:ro"  # Map the Traefik config file
      - "./acme.json:/acme.json"        # Map the ACME storage file
      - "/var/run/docker.sock:/var/run/docker.sock:ro"  # Docker socket for Traefik to detect services
    ports:
      - "80:80"    # HTTP
      - "443:443"  # HTTPS
    networks:
      - traefik-public
    deploy:
      placement:
        constraints:
          - node.role == manager
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.api.rule=Host(`your-domain.com`)"
        - "traefik.http.routers.api.entrypoints=websecure"
        - "traefik.http.routers.api.tls.certresolver=letsencrypt"
        - "traefik.http.routers.api.service=api@internal"
        # Dummy service to prevent "port is missing" error
        - "traefik.http.services.dummy-service.loadbalancer.server.port=1337"

networks:
  traefik-public:
    external: true
